### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by artkoci** [artkoci/FitnessBanking#1]
# Plan

- [x] Open bunq account and name it "Run fat boy run"
- [x] Sort out Strava
- [ ] Sort out bunq
- [ ] Make it work
